package ie.turfclub.vetReports.model;
// default package
// Generated 12-Dec-2014 13:59:03 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VetreportHorsesId generated by hbm2java
 */
@Entity
@Table(name = "vetreport_horses_not_ran", catalog = "vetreports")
public class VetreportHorsesNotRan implements java.io.Serializable {

	private Integer notRanId;
	private String notRanHorseName;


	public VetreportHorsesNotRan() {
		
	}

	

	public VetreportHorsesNotRan(Integer notRanId, String notRanHorseName) {
	
		this.notRanId = notRanId;
		this.notRanHorseName = notRanHorseName;
	}



	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "not_ran_id", nullable = false)
	public Integer getNotRanId() {
		return notRanId;
	}



	public void setNotRanId(Integer notRanId) {
		this.notRanId = notRanId;
	}


	@Column(name = "not_ran_horse_name")
	public String getNotRanHorseName() {
		return notRanHorseName;
	}



	public void setNotRanHorseName(String notRanHorseName) {
		this.notRanHorseName = notRanHorseName;
	}



}
