package ie.turfclub.vetReports.model;
// default package
// Generated 12-Dec-2014 13:59:03 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VetreportTrainersId generated by hbm2java
 */
@Entity
@Table(name = "vetreport_trainers", catalog = "vetreports")
public class VetreportTrainers implements java.io.Serializable {

	private Integer trainerId;
	private String trainerName;

	public VetreportTrainers() {

	}

	public VetreportTrainers(Integer trainerId, String trainerName) {
		this.trainerId = trainerId;
		this.trainerName = trainerName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "trainer_id", nullable = false)
	public Integer getTrainerId() {
		return this.trainerId;
	}

	public void setTrainerId(Integer trainerId) {
		this.trainerId = trainerId;
	}

	@Column(name = "trainer_name", nullable = false, length = 200)
	public String getTrainerName() {
		return this.trainerName;
	}

	public void setTrainerName(String trainerName) {
		this.trainerName = trainerName;
	}



	
}
