package ie.turfclub.vetReports.model;
// default package
// Generated 12-Dec-2014 13:59:03 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

/**
 * VetreportHorsesId generated by hbm2java
 */
@Entity
@Table(name = "vetreport_horses", catalog = "vetreports")
public class VetreportHorses implements java.io.Serializable {

	private Integer horseId;
	private String horseName;
	private VetreportRacecard horseLastRacecardId;

	public VetreportHorses() {
		
	}

	public VetreportHorses(Integer horseId, String horseName) {
		this.horseId = horseId;
		this.horseName = horseName;
	}

	public VetreportHorses(Integer horseId, String horseName,
			VetreportRacecard horseLastRacecardId) {
		this.horseId = horseId;
		this.horseName = horseName;
		this.horseLastRacecardId = horseLastRacecardId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "horse_id", nullable = false)
	public Integer getHorseId() {
		return this.horseId;
	}

	public void setHorseId(Integer horseId) {
		this.horseId = horseId;
	}

	@Column(name = "horse_name", nullable = false, length = 200)
	public String getHorseName() {
		return this.horseName;
	}

	public void setHorseName(String horseName) {
		this.horseName = horseName;
	}

	
	@Basic(optional=true)
	@NotFound(action=NotFoundAction.IGNORE)  
	@OneToOne( optional = true, fetch = FetchType.EAGER)
	@JoinColumn(name = "horse_last_racecard_id", nullable = true)
	public VetreportRacecard getHorseLastRacecardId() {
		return this.horseLastRacecardId;
	}

	public void setHorseLastRacecardId(VetreportRacecard horseLastRacecardId) {
		this.horseLastRacecardId = horseLastRacecardId;
	}


}
