package ie.turfclub.vetReports.model;

// default package
// Generated 12-Nov-2014 16:48:32 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

/**
 * VetreportAlertHorses generated by hbm2java
 */
@Entity
@Table(name = "vetreport_alert_horses", catalog = "vetreports")
public class VetreportAlertHorses implements java.io.Serializable {

	private Integer alertHorseAlertId;
	private String alertHorseId;
	private VetreportRacecard reportRacecardId;

	public VetreportAlertHorses() {

	}

	public VetreportAlertHorses(String alertHorseId) {
		this.alertHorseId = alertHorseId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "alert_horse_alert_id", unique = true, nullable = false)
	public Integer getAlertHorseAlertId() {
		return this.alertHorseAlertId;
	}

	public void setAlertHorseAlertId(Integer alertHorseAlertId) {
		this.alertHorseAlertId = alertHorseAlertId;
	}

	@Column(name = "alert_horse_id", nullable = false)
	public String getAlertHorseId() {
		return this.alertHorseId;
	}

	public void setAlertHorseId(String alertHorseId) {
		this.alertHorseId = alertHorseId;
	}

	@Basic(optional=true)
	@NotFound(action=NotFoundAction.IGNORE)  
	@OneToOne( optional = true, fetch = FetchType.EAGER)
	@JoinColumn(name = "alert_racecard_id", nullable = true)
	public VetreportRacecard getReportRacecardId() {
		return reportRacecardId;
	}

	public void setReportRacecardId(VetreportRacecard reportRacecardId) {
		this.reportRacecardId = reportRacecardId;
	}
	


	

}
