package ie.turfclub.main.pojos.directives;

public enum DirectiveTypes {
	//Display Directives
	DATESPAN,SPAN,MULTIBUTTON,BUTTON,TRUEFALSETICKWITHBUTTON,CONTACTDETAILS,TRUEFALSETICK,ENUMTOIMAGE,
	//Form Directive Types
	INPUT,SELECT2,SELECT2MULTI,SELECTBOOLEAN, SELECTENUMIMAGE, SELECT2LINKED,DATEPICKERDIR,DATEPICKERFROMTODIR,FILLFIELDSBUTTON,COMMENTBOX,COMMENTBOXENUMTOGGLE 
}
