package ie.turfclub.inspections.model;

// default package
// Generated 13-Feb-2015 16:15:13 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * InspectionsHandlers generated by hbm2java
 */
@Entity
@Table(name = "inspections_handlers", catalog = "inspections")
public class InspectionsHandlers implements java.io.Serializable {

	private int ownerId;
	private String ownerFirstName;
	private String ownerAccountNo;
	private String ownerSurname;
	private String ownerAddress1;
	private String ownerAddress2;
	private String ownerAddress3;
	private String ownerAddress4;
	private String ownerMobileNo;
	private String ownerPhoneNo;
	private String ownerEmail;
	private Date ownerDateOfBirth;
	private String ownerHriAccNo;
	private String ownerStatus;

	public InspectionsHandlers() {
	}

	public InspectionsHandlers(int ownerId, String ownerFirstName,
			String ownerAccountNo, String ownerSurname, String ownerAddress1,
			String ownerAddress2, String ownerAddress3, String ownerAddress4,
			String ownerMobileNo, String ownerPhoneNo, String ownerEmail,
			Date ownerDateOfBirth, String ownerHriAccNo, String ownerStatus) {
		this.ownerId = ownerId;
		this.ownerFirstName = ownerFirstName;
		this.ownerAccountNo = ownerAccountNo;
		this.ownerSurname = ownerSurname;
		this.ownerAddress1 = ownerAddress1;
		this.ownerAddress2 = ownerAddress2;
		this.ownerAddress3 = ownerAddress3;
		this.ownerAddress4 = ownerAddress4;
		this.ownerMobileNo = ownerMobileNo;
		this.ownerPhoneNo = ownerPhoneNo;
		this.ownerEmail = ownerEmail;
		this.ownerDateOfBirth = ownerDateOfBirth;
		this.ownerHriAccNo = ownerHriAccNo;
		this.ownerStatus = ownerStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "owner_id", nullable = false)
	public int getOwnerId() {
		return this.ownerId;
	}

	public void setOwnerId(int ownerId) {
		this.ownerId = ownerId;
	}

	@Column(name = "owner_first_name", nullable = false, length = 200)
	public String getOwnerFirstName() {
		return this.ownerFirstName;
	}

	public void setOwnerFirstName(String ownerFirstName) {
		this.ownerFirstName = ownerFirstName;
	}

	@Column(name = "owner_account_no", nullable = false, length = 200)
	public String getOwnerAccountNo() {
		return this.ownerAccountNo;
	}

	public void setOwnerAccountNo(String ownerAccountNo) {
		this.ownerAccountNo = ownerAccountNo;
	}

	@Column(name = "owner_surname", nullable = false, length = 200)
	public String getOwnerSurname() {
		return this.ownerSurname;
	}

	public void setOwnerSurname(String ownerSurname) {
		this.ownerSurname = ownerSurname;
	}

	@Column(name = "owner_address1", nullable = false, length = 200)
	public String getOwnerAddress1() {
		return this.ownerAddress1;
	}

	public void setOwnerAddress1(String ownerAddress1) {
		this.ownerAddress1 = ownerAddress1;
	}

	@Column(name = "owner_address2", nullable = false, length = 200)
	public String getOwnerAddress2() {
		return this.ownerAddress2;
	}

	public void setOwnerAddress2(String ownerAddress2) {
		this.ownerAddress2 = ownerAddress2;
	}

	@Column(name = "owner_address3", nullable = false, length = 200)
	public String getOwnerAddress3() {
		return this.ownerAddress3;
	}

	public void setOwnerAddress3(String ownerAddress3) {
		this.ownerAddress3 = ownerAddress3;
	}

	@Column(name = "owner_address4", nullable = false, length = 200)
	public String getOwnerAddress4() {
		return this.ownerAddress4;
	}

	public void setOwnerAddress4(String ownerAddress4) {
		this.ownerAddress4 = ownerAddress4;
	}

	@Column(name = "owner_mobile_no", nullable = false, length = 200)
	public String getOwnerMobileNo() {
		return this.ownerMobileNo;
	}

	public void setOwnerMobileNo(String ownerMobileNo) {
		this.ownerMobileNo = ownerMobileNo;
	}

	@Column(name = "owner_phone_no", nullable = false, length = 200)
	public String getOwnerPhoneNo() {
		return this.ownerPhoneNo;
	}

	public void setOwnerPhoneNo(String ownerPhoneNo) {
		this.ownerPhoneNo = ownerPhoneNo;
	}

	@Column(name = "owner_email", nullable = false, length = 200)
	public String getOwnerEmail() {
		return this.ownerEmail;
	}

	public void setOwnerEmail(String ownerEmail) {
		this.ownerEmail = ownerEmail;
	}

	@Column(name = "owner_date_of_birth", nullable = false, length = 10)
	public Date getOwnerDateOfBirth() {
		return this.ownerDateOfBirth;
	}

	public void setOwnerDateOfBirth(Date ownerDateOfBirth) {
		this.ownerDateOfBirth = ownerDateOfBirth;
	}

	@Column(name = "owner_hri_acc_no", nullable = false, length = 200)
	public String getOwnerHriAccNo() {
		return this.ownerHriAccNo;
	}

	public void setOwnerHriAccNo(String ownerHriAccNo) {
		this.ownerHriAccNo = ownerHriAccNo;
	}

	@Column(name = "owner_status", nullable = false, length = 200)
	public String getOwnerStatus() {
		return this.ownerStatus;
	}

	public void setOwnerStatus(String ownerStatus) {
		this.ownerStatus = ownerStatus;
	}

}
