package ie.turfclub.inspections.model;

// default package
// Generated 11-Feb-2015 16:52:50 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

/**
 * InspectionsStatus generated by hbm2java
 */
@Entity
@Table(name = "inspections_sub_categories", catalog = "inspections")
public class InspectionsSubCategories implements java.io.Serializable {

	private Integer subCatId;
	private String subCatName;
	private InspectionsCategories subCatCategoryId;		

	public InspectionsSubCategories() {
	}

	

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sub_cat_id", unique = true, nullable = false)
	public Integer getSubCatId() {
		return subCatId;
	}

	public void setSubCatId(Integer subCatId) {
		this.subCatId = subCatId;
	}
	@Column(name = "sub_cat_name", nullable = false, length = 200)
	public String getSubCatName() {
		return subCatName;
	}

	public void setSubCatName(String subCatName) {
		this.subCatName = subCatName;
	}

	@Basic(optional=true)
	@NotFound(action=NotFoundAction.IGNORE)  
	@OneToOne( optional = true, fetch = FetchType.EAGER)
	@JoinColumn(name = "sub_cat_category_id", nullable = true)
	public InspectionsCategories getSubCatCategoryId() {
		return subCatCategoryId;
	}

	public void setSubCatCategoryId(InspectionsCategories subCatCategoryId) {
		this.subCatCategoryId = subCatCategoryId;
	}

	
	
	
}
