package ie.turfclub.inspections.model;

// default package
// Generated 13-Feb-2015 16:15:13 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * InspectionsHandlers generated by hbm2java
 */
@Entity
@Table(name = "inspections_unregistered_persons", catalog = "inspections")
public class InspectionsUnregistered implements java.io.Serializable {

	private int unregId;
	private String unregFirstName;
	private String unregSurname;
	private String unregAddress1;
	private String unregAddress2;
	private String unregAddress3;
	private String unregAddress4;
	
	
	public InspectionsUnregistered() {
	}



	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "unreg_id", nullable = false)
	public int getUnregId() {
		return unregId;
	}



	public void setUnregId(int unregId) {
		this.unregId = unregId;
	}
	
	

	@Column(name = "unreg_first_name", nullable = false, length = 200)
	public String getUnregFirstName() {
		return unregFirstName;
	}



	public void setUnregFirstName(String unregFirstName) {
		this.unregFirstName = unregFirstName;
	}



	@Column(name = "unreg_surname", nullable = false, length = 200)
	public String getUnregSurname() {
		return unregSurname;
	}



	public void setUnregSurname(String unregSurname) {
		this.unregSurname = unregSurname;
	}


	@Column(name = "unreg_address1", nullable = false, length = 200)
	public String getUnregAddress1() {
		return unregAddress1;
	}



	public void setUnregAddress1(String unregAddress1) {
		this.unregAddress1 = unregAddress1;
	}


	@Column(name = "unreg_address2", nullable = false, length = 200)
	public String getUnregAddress2() {
		return unregAddress2;
	}



	public void setUnregAddress2(String unregAddress2) {
		this.unregAddress2 = unregAddress2;
	}


	@Column(name = "unreg_address3", nullable = true, length = 200)
	public String getUnregAddress3() {
		return unregAddress3;
	}



	public void setUnregAddress3(String unregAddress3) {
		this.unregAddress3 = unregAddress3;
	}


	@Column(name = "unreg_address4", nullable = true, length = 200)
	public String getUnregAddress4() {
		return unregAddress4;
	}



	public void setUnregAddress4(String unregAddress4) {
		this.unregAddress4 = unregAddress4;
	}



}
